/*
 * @(#)Rockolav2.java 1.82 09/10/19
 *
 * Armando Rivera Cervantes
 * Copyright (c) Inc.
 * Iztapalapa CDMX México
 * Todos los derechos reservados.
 *
 * Más información y descripción del Copyright.
 *
 */

package Ventanas;

import java.awt.Color;

/**
 *
 * @author ArmandRC
 */
public class Primaria extends javax.swing.JFrame {

    /**
     * Creates new form Primaria
     */
    public Primaria() {
        initComponents();
        this.getContentPane().setBackground(Color.GRAY);
        this.setLocationRelativeTo(null);
        this.setTitle("Rocko UACM");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laUsuario = new javax.swing.JLabel();
        but60 = new javax.swing.JButton();
        butPreferencias = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        butStop = new javax.swing.JButton();
        butPausa = new javax.swing.JButton();
        butPlay = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSlider1 = new javax.swing.JSlider();
        volumen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        nombreCan = new javax.swing.JLabel();
        butCerrar = new javax.swing.JButton();
        butPerfil = new javax.swing.JButton();
        butLike = new javax.swing.JButton();
        but70 = new javax.swing.JButton();
        but80 = new javax.swing.JButton();
        but90 = new javax.swing.JButton();
        butBusca = new javax.swing.JButton();
        textBusca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTodas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(687, 607));
        setMinimumSize(new java.awt.Dimension(687, 607));
        setPreferredSize(new java.awt.Dimension(687, 607));
        setSize(new java.awt.Dimension(687, 607));

        laUsuario.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        laUsuario.setText("Usuario");

        but60.setText("60's");
        but60.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        butPreferencias.setText("Preferencias");
        butPreferencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butPreferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPreferenciasActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disc.png"))); // NOI18N

        butStop.setBackground(new java.awt.Color(255, 255, 255));
        butStop.setForeground(new java.awt.Color(255, 255, 255));
        butStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/media_playback_stop.png"))); // NOI18N
        butStop.setBorderPainted(false);
        butStop.setContentAreaFilled(false);
        butStop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        butPausa.setBackground(new java.awt.Color(255, 255, 255));
        butPausa.setForeground(new java.awt.Color(255, 255, 255));
        butPausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/media_playback_pause.png"))); // NOI18N
        butPausa.setBorderPainted(false);
        butPausa.setContentAreaFilled(false);
        butPausa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        butPlay.setBackground(new java.awt.Color(255, 255, 255));
        butPlay.setForeground(new java.awt.Color(255, 255, 255));
        butPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play_win7.png"))); // NOI18N
        butPlay.setBorderPainted(false);
        butPlay.setContentAreaFilled(false);
        butPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSlider1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        volumen.setText("Volumen");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        nombreCan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreCan.setText("Titulo");

        butCerrar.setText("Cerrar cuenta");
        butCerrar.setContentAreaFilled(false);
        butCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        butPerfil.setText("Modificar Perfil");
        butPerfil.setContentAreaFilled(false);
        butPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        butLike.setBackground(new java.awt.Color(255, 255, 255));
        butLike.setForeground(new java.awt.Color(255, 255, 255));
        butLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/like.png"))); // NOI18N
        butLike.setBorderPainted(false);
        butLike.setContentAreaFilled(false);
        butLike.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butLike.setDefaultCapable(false);

        but70.setText("70's");
        but70.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        but80.setText("80's");
        but80.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        but90.setText("90´s");
        but90.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        butBusca.setText("Buscar");
        butBusca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscaActionPerformed(evt);
            }
        });

        jLabel1.setText("<---Ingresa nombre de artista, album o canción.");

        jTodas.setText("todas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butPreferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butBusca)
                        .addGap(28, 28, 28)
                        .addComponent(textBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(254, 254, 254)
                            .addComponent(jTodas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(butPerfil)
                                    .addGap(31, 31, 31)
                                    .addComponent(butCerrar))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(87, 87, 87)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(butLike)
                                        .addComponent(laUsuario)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(but60, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(but70, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(but80, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(but90, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(volumen)
                            .addGap(32, 32, 32)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreCan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butStop)
                .addGap(18, 18, 18)
                .addComponent(butPausa)
                .addGap(18, 18, 18)
                .addComponent(butPlay)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butBusca)
                    .addComponent(textBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but60)
                    .addComponent(but70)
                    .addComponent(but80)
                    .addComponent(but90))
                .addGap(18, 18, 18)
                .addComponent(butPreferencias)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(nombreCan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butPerfil)
                            .addComponent(butCerrar))
                        .addGap(18, 18, 18)
                        .addComponent(laUsuario)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butLike)
                            .addComponent(jTodas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(butPlay)
                                .addComponent(butPausa, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(butStop))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volumen))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butPreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPreferenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butPreferenciasActionPerformed

    private void butBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Primaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Primaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Primaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Primaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Primaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton but60;
    public javax.swing.JButton but70;
    public javax.swing.JButton but80;
    public javax.swing.JButton but90;
    public javax.swing.JButton butBusca;
    public javax.swing.JButton butCerrar;
    public javax.swing.JButton butLike;
    public javax.swing.JButton butPausa;
    public javax.swing.JButton butPerfil;
    public javax.swing.JButton butPlay;
    public javax.swing.JButton butPreferencias;
    public javax.swing.JButton butStop;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JList<String> jList1;
    public javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JSlider jSlider1;
    public javax.swing.JLabel jTodas;
    public javax.swing.JLabel laUsuario;
    public javax.swing.JLabel nombreCan;
    public javax.swing.JTextField textBusca;
    private javax.swing.JLabel volumen;
    // End of variables declaration//GEN-END:variables
}
